# Generated by Django 4.1.7 on 2023-03-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0005_remove_transactions_accoun_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='account_balance',
        ),
    ]
