# Generated by Django 4.1.7 on 2023-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0008_portfolio_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='customer',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='customer',
            new_name='username',
        ),
    ]
