# Generated by Django 4.1.7 on 2023-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0011_alter_balance_accoun_total_alter_portfolio_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='account_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
