# Generated by Django 4.2 on 2023-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0016_rename_phone_portfolio_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
