# Generated by Django 4.2 on 2023-06-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0019_shoppingtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingtransaction',
            old_name='user',
            new_name='username',
        ),
    ]
