# Generated by Django 4.1.7 on 2023-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0002_alter_portfolio_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accoun_total', models.IntegerField()),
                ('account_balance', models.IntegerField()),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('bank_address', models.CharField(max_length=200)),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=200)),
                ('amount_to_transfer', models.IntegerField()),
                ('beneficiary_email', models.EmailField(max_length=200)),
                ('beneficiary_phone_number', models.IntegerField()),
                ('bank_swift_code', models.IntegerField()),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
