# Generated by Django 4.1.7 on 2023-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0003_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='accoun_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
