# Generated by Django 4.1.7 on 2023-03-03 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novabank', '0004_alter_transactions_accoun_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='accoun_total',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='pin',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novabank.portfolio'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accoun_total', models.IntegerField()),
                ('account_balance', models.IntegerField()),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novabank.portfolio')),
            ],
        ),
    ]
