# Generated by Django 4.1.7 on 2023-03-21 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0009_rename_customer_balance_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
