# Generated by Django 4.1.7 on 2023-03-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0012_portfolio_account_total_portfolio_pin_delete_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='account_total',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pin',
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accoun_total', models.IntegerField(blank=True, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='novabank.portfolio')),
            ],
        ),
    ]
