# Generated by Django 4.2 on 2023-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novabank', '0013_remove_portfolio_account_total_remove_portfolio_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='accoun_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
